spring:
  application:
    name: ZokaLocaBackend
  profiles:
    active: e2e

  asset.storage:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: zokaloca

server:
  port: '8080'

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
  root-user:
    email: a.gosens@student.fontys.nl
    first-name: Arjan
    last-name: Gosens
    password: Qwerty123!