spring:
  application:
    name: ZokaLocaBackend

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: zokaloca

server:
  port: '8080'

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day